config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/cart'
  resources :products

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

app/models/address.rb
class Address
  include Mongoid::Document
  field :name, type: String
  field :phone, type: Integer
  field :email, type: String
  field :address_line1, type: String
  field :address_line2, type: String

end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time


  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :price, type: Float
  field :main_image, type: String
  field :thumb_image, type: String
  

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_image, ImageUploader

  validates :title, :description, presence: true
  validates :title, uniqueness: true
  validates :price, format: { with:/\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }, uniqueness: true
  
  #Creating an object
  before_validation :before_validation_method
  after_validation :after_validation_method
  before_save :before_saving_an_object
  before_create :before_create
  after_create :after_create 
  after_save :after_saving

  # updating an object
  before_update :set_price

  # Destroying an object
  before_destroy :deleting_last_record

  def before_validation_method
    puts "Invoked before validation and changed title to #{self.title = title.upcase}"
  end

  def after_validation_method
    if self.errors.any?
      puts "Validation failed when creating a product"
      puts self.errors.messages
    else 
      puts "Invoked after_validation method"
    end
  end

  def before_saving_an_object
    puts "Invoked before_save and the product with #{self.title} is yet to be saved"
  end

  def before_create
    puts "Invoked before create method"
    puts "Title is changed to #{self.title = "#{title.downcase}"}"
  end

  def after_create
    puts "Invoked After create method"
  end

  def after_saving
    puts "invoking after saving method"
  end

  #updating the price
  def set_price
    puts "update price: "
    self.price = gets  
    puts "Updated price: #{self.price}, \nTitle: #{self.title}, \nDescription: #{self.description}"
  end

  #destroy an object
  def deleting_last_record
    puts "Deleted the product with title #{self.title}"
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  embeds_many :addresses

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/addresses_controller.rb
class AddressesController < InheritedResources::Base
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
	@addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
  	@address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  def create
  	@address = Address.new(address_params)

  	respond_to do |format|
  		if @address.save
  			format.html { redirect_to @address, notice: 'address was successfully created.' }
  			format.json { render :show, status: :created, location: @address }
  		else
  			format.html { render :new }
  			format.json { render json: @address.errors, status: :unprocessable_entity }
  		end
  	end
  end

  private

  def set_address
  @address = Address.find(params[:id])
  end

  def address_params
  	params.require(:address).permit(:name, :phone, :email, :address_line1, :address_line2)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    layout 'page'

  def home
  end

  def about
  end

  def cart 
  	if user_signed_in?
  		pages_cart_path
  	else 
  		new_user_session_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  before_action :set_product, only: [:show, :edit, :update, :destroy, :about]
  layout 'product'

  def index
    @products = Product.all
  end

  def about
  end
  
  def show
  end

  def new
    @product = Product.new
  end

  def create
   @product = Product.new(product_params)

   respond_to do |format|
    if @product.save
     format.html { redirect_to @product, notice: 'Product was successfully created.' }
     format.json { render :show, status: :created, location: @product }
   else
     format.html { render :new }
     format.json { render json: @product.errors, status: :unprocessable_entity }
   end
 end
end


private
def set_product
  @product = Product.find(params[:id])
end

def product_params
  params.require(:product).permit(:title, :description, :price, :main_image, :thumb_image)
end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def present(object, klass = nil)
		klass ||= "#{object.class}Presenter".constantize 
		presenter = klass.new(object, self)
		yield presenter if block_given?
		presenter
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def image_generator(height: , width:)
		"http://placehold.it/#{height} x #{width}"
	end	

	def product_image img, type
		if img
			img
		elsif type =='thumb'
			image_generator(height: 350 , width: 200)
		else type == 'main'
			image_generator(height: 350 , width: 200)
		end
	end
end

app/views/addresses/_form.html.erb
<div class="modal-content">
  <%= form_with(model: address, local: true) do |form| %>
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Add Address</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>


    <div class="modal-body">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.number_field :phone %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>

      <div class="form-group">
        <%= form.label :address_line1 %>
        <%= form.text_field :address_line1 %>
      </div>

      <div class="form-group">
        <%= form.label :address_line2 %>
        <%= form.text_field :address_line2 %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address line1</th>
      <th>Address line2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.name %></td>
        <td><%= address.phone %></td>
        <td><%= address.email %></td>
        <td><%= address.address_line1 %></td>
        <td><%= address.address_line2 %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @address.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @address.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @address.email %>
</p>

<p>
  <strong>Address line1:</strong>
  <%= @address.address_line1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @address.address_line2 %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcommerceApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>

<body>
  <div class="container-fluid">
    <%= render "layouts/shared/header" %>    
    <%= yield %>
  </div>
</body>

</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products | Shopping Zone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag 'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
</head>

  <body>
   <div class="container-fluid">
      <%= render "layouts/shared/header" %>    
    </div>
    <div id='background-image'>
    </div>
    <div class="container">
        <%= yield %>
    </div>
 
  </body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products | Shopping Zone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag 'products', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  
</head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/shared/header" %>    
    </div>
    
    <div class="container">
        <%= yield %>

    </div>
 
  </body>
</html>

app/views/layouts/shared/_banner.html.erb
 <section class= "mt-2">
  <div>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="first-slide"  src="http://www.justinstellman.com/wp-content/uploads/2017/04/reading-book.jpg"
          alt="First slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-left ">
              <div style="color: white;">
                <h3 >Top Rated Books</h3>
                <p>“Never trust anyone who has not brought a book with them.” – Lemony Snicket</p>
                <p> 
                  <% if current_user %>
                  <%= %>
                  <% else %>
                  <%= link_to "Sign up today", new_user_registration_path, class:"btn btn-sm btn-primary" %>
                  <% end %>
                  </p>
              </div>
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <img class="second-slide" src="https://marketingweek.imgix.net/content/uploads/2017/07/28131730/read-book_750.jpg?auto=compress,enhance,format,redeye&crop=faces,entropy,edges&fit=crop&q=60&w=750&h=460" alt="Second slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block ">
              <div class= "slide1-font" >
                <h1>Top Rated Books</h1>
                <p>“Think before you speak. Read before you think.” – Fran Lebowitz</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <img class="third-slide"  src="https://education.cu-portland.edu/wp-content/uploads/sites/33/2018/03/Book-Flood.png" alt="Third slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-right">
             <div style="color: black;">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</section>

app/views/layouts/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><a href="https://twitter.com/mdo" class="footer" >© 2019</a> | Trika Technologies <a href="https://getbootstrap.com"></a>| All rights are reserved.</p>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/products/">Ecommerce App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarCollapse">
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/pages/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="/pages/contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products/">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fa fa-cart-plus mt-1" href="/pages/cart/">&nbsp; Cart</a>
        </li>
      </ul>

      <% if current_user %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link", style:"color: #c7c7c7" %>
      <% end %>
     
    </div>
  </nav>
</header>

app/views/layouts/shared/_products_banner.html.erb
 <section class= "mt-2">
  <div>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <%= image_tag product_image(@product.main_image_url, 'main') %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-left ">
              <div style="color: white;">
                <h3 ></h3>
                <p></p>
              </div>
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <%= image_tag product_image(@product.thumb_image_url, 'thumb') %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block ">
              
            </div>
          </div>
        </div>

    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</section>
	

app/views/pages/about.html.erb
<div class="about">
	
	<h1>About Shopping Zone</h1>
	<div class= 'row'>
		<div class ='col-md-3' style="margin-top: 3rem;">
			<%= image_tag "about.jpg", width: 320, alt: "about image" %>
		</div>

		<div class ='col-md-9 ' style="margin-top: 3rem;">
			<p>Welcome to Shopping Zone, your number one source for all things  ie: technical books, ecommerce and all varities of books. We're dedicated to giving you the very best of product, with a focus on three characteristics, ie: dependability, customer service and uniqueness.
			Founded in 2019 by Sathya teja Daggubati</p>
			<p>Shopping Zone has come a long way from its beginnings. When store founder first started out, his/her passion for [passion of founder, ie: helping other parents be more eco-friendly, providing the best equipment for his fellow musicians] drove him to [action, ie: do intense research, quit her day job], and gave him the impetus to turn hard work and inspiration into to a booming online store. We now serve customers all over [place, ie: the US, the world, the Austin area], and are thrilled to be a part of the [adjective, ie: quirky, eco-friendly, fair trade] wing of the [industry type, ie: fashion, baked goods, watches] industry.</p>
			
		</div>
	</div>
</div>

app/views/pages/cart.html.erb
<div class= "contact">

	<div class="row">

      <% if current_user %>
			<div class="col-12 col-md-8 col-sm-6 col-lg-6 text-center" style="border-color: white; color: white;">
				My Cart Items
				<hr>
			</div>
			<div class="col-6 col-md-4 text-center" id= "address">
				<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addressModel">
				 Add Address
				</button>


			  <!-- Modal -->
			  <div class="modal fade" data-backdrop="static" id="addressModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			    <div class="modal-dialog modal-dialog-centered" role="document">
			      <%= render 'addresses/form', address: @address, remote: true %>
			    </div>
			  </div>

			</div>
		<% else %>
			<div class="col-12 col-md-8 col-sm-6 col-lg-8 text-center" style="border-color: white; color: white;">
				My Cart Items
				<hr>
			</div>
			<div class="col-md-4 text-center">
			 <%= link_to "Login", new_user_session_path, class: "btn btn-primary text-center" %>
			</div>
		<% end %>

	</div>
</div>

app/views/pages/contact.html.erb
<div class= "contact">

  <h2>Would you like to work together?</h2>

  <hr>

  <div class="row">
    <div class="col-md-7">
      <h3>Office Address</h3>

      <p>1223 Brookefield Rd, Bangalore, KA 94839</p>

      <h3>Phone</h3>

      <p><%= number_to_phone "9398274181" %></p>

      <h3>Email</h3>

      <p><a href="https://accounts.google.com/signin/v2/identifier?hl=en&continue=https%3A%2F%2Fmail.google.com%2Fmail&service=mail&flowName=GlifWebSignIn&flowEntry=AddSession" >Email me</a> </p>
    </div>

    <div class= "col-md-5">
     <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15552.22755724086!2d77.7054493701771!3d12.968211553728288!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x62e339c426312e20!2sGopalan+Coworks%2CWhitefield!5e0!3m2!1sen!2sin!4v1562132624758!5m2!1sen!2sin" width="300" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
   </div>
 </div>

</div>

app/views/pages/home.html.erb
<main role="main" class="inner cover col-sm-6 col-md-6 col-xs-6 col-lg-12 col-md-12 home">
	<h1 class="cover-heading" >Welcome</h1>
	<hr>
	<p class="lead" style= "font-style: oblique;">“We see our customers as invited guests to a party, and we are the hosts. It’s our job every day to make every important aspect of the customer experience a little bit better."</p>
	<p class="lead">
		<%= link_to " Contact", pages_contact_path, class: "btn btn-info fa fa-address-book-o"%>
	</p>
</main>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%=form.label :main_image %>
    <%= image_tag form.file_field :main_image, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :thumb_image %>
    <%=  form.file_field :thumb_image, multiple: true  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
    <div class="col-md-3 col-lg-3 col-xs-6">
    	<div class='singleCard'>
      		<a href= "/products/<%=product.id%>">

      		<div class="singleImg">
      		<%= image_tag product_image(product.main_image_url, 'main') %>
      		</div>

      		</a>
			<p class= "card-text">
				<span ><%= link_to product.title, product_path(product) %></span>
				<p>Price: $<%= link_to product.price, product_path(product), style: "color:black" %></p>
			</p>
		</div>
    </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<!-- banner -->
<%= render "layouts/shared/banner" %>
<%= t "products.title" %>
<div class= "container">
	  <div class="row">
<%= render partial: 'product', collection: @products %>
</div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% present @product do |product_presenter| %>
	<div class= "row mt-2">
		<div class= "col-12 col-sm-7 col-md-7 show-banner">
			<%= render "layouts/shared/products_banner" %>
			<div class= "row">
				<%= product_presenter.add_to_cart%>
				<button class="btn btn-info ml-auto" type="button">
					BUY NOW
				</button>
			</div>
		</div>

		<div class= "col-12 col-sm-4 col-md-4 show-banner">
			<h3>Title: </h3>
			<p><%= @product.title %></p>
			<hr>
			<h3>Description: </h3>
			<hr>
			<p><%= @product.description %></p>
			<h3>Price: </h3>
			<hr>
			<p>$<%= @product.price %></p>

			<%= link_to 'Back', products_path %>
		</div>
	</div>
<%end %>